- name: Execute Router Upgrade Script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run the Python script with parameters
      command: "/var/lib/awx/venv/python-scripts/python-scripts/bin/python3 /var/lib/awx/venv/python-scripts/auto_upgrade.py --router_ip={{ router_ip }} --emergency_phone={{ emergency_phone }}"
