---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: running_config

    - name: Save config to container tmp
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/tmp/show_run_{{ inventory_hostname }}.txt"
        mode: '0644'

    - name: Copy config file from /tmp to host-mounted project directory
      copy:
        src: "/tmp/show_run_{{ inventory_hostname }}.txt"
        dest: "/var/lib/awx/projects/_16__cisco_backups/backups/show_run_{{ inventory_hostname }}.txt"
        remote_src: yes
