---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: running_config

    - name: Show what would be written to file
      debug:
        msg: "{{ running_config.stdout[0][:500] }}"
      
    - name: Backup running config
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: /etc/ansible/backups/show_run_{{ inventory_hostname }}.txt
        mode: '0755'
      delegate_to: localhost

