---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: running_config

    - name: Ensure backup directory exists on control node
     file:
       path: /etc/ansible/backups
       state: directory
       mode: '0755'
     delegate_to: localhost
      
    - name: Backup running config
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: /etc/ansible/backups/show_run_{{ inventory_hostname }}.txt
        mode: '0755'
      delegate_to: localhost

