---
- hosts: all
  become: false
  gather_facts: false

  tasks:
   - name: show run
     ios_config:
       backup_options:
         path: /etc/ansible/backups/
         filename: "show_run_{{ inventory_hostname }}.txt"
