---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: running_config

    - name: Save config to container tmp
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/tmp/show_run_{{ inventory_hostname }}.txt"
        mode: '0644'

    - name: Fetch config file to host backups directory
      fetch:
         src: "/tmp/show_run_{{ inventory_hostname }}.txt"
         dest: "/var/lib/awx/projects/_16__cisco_backups/backups"
         flat: yes
