---
- hosts: all
  gather_facts: false
  become: false

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config
     
   - name: save output to /home/mneely/ansible/backups/
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/tmp/show_run_{{ inventory_hostname }}.txt"
       mode: 0755
     delegate_to: localhost
     
   - name: fetch output from remote host to Tower
     fetch:
       src: "/tmp/show_run_{{ inventory_hostname }}.txt"
       dest: /tmp/      # A subdir under /tmp will be created by default, named after the remote host, where the show_run_... file will be stored.

