---
- hosts: all
  become: yes
  gather_facts: false

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config
     connection: local
     
   - name: save output to /home/mneely/ansible/backups/
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"
       mode: 0755
     delegate_to: localhost
