---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Backup Cisco running configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: show_run_{{ inventory_hostname }}.txt
          dir_path: /home/mneely/backups
