---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: running_config
      
    - name: Backup running config
      copy:
        content: "{{ running_config.results[0].stdout }}"
        dest: /etc/ansible/backups/show_run_{{ inventory_hostname }}.txt
        mode: 755
      delegate_to: localhost

