---
- hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config
   - name: save output to /home/mneely/ansible/backups/
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/opt/backups/show_run_{{ inventory_hostname }}.txt"
       mode: 0755
