--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      var: 
        customer_name: "{{ CustomerName }}"
        data_center: "{{ DataCenter }}"
        evpn_id: "{{ EVPN_ID }}"
        ip_address: "{{ BVI_IP }}"
        prefix_mask: "{{ MASK }}"
    - 
      debug: 
        msg: vars
