--- 
- 
  connection: network_cli
  gather_facts: false
  hosts: '{{ DataCenter }}'
   
  vars: 
    customer_name: "{{ CustomerName }}"
    data_center: "{{ DataCenter }}"
    evpn_id: "{{ EVPN_ID }}"
    ip_address: "{{ BVI_IP }}"
    prefix_mask: "{{ MASK }}"
        
  tasks:
  
    - debug: 
        msg: "{{ EVPN_ID }}"
        
    - name: Config Router EVPN
      iosxr_config: 
        lines:
          - evi "{{ evpn_id }}"
          - control-word-disable
          - advertise-mac
        parents: evpn
    
    
   
        
