--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    debug: 
      msg: vars
    vars: 
      customer_name: "{{ CustomerName }}"
      data_center: "{{ DataCenter }}"
      evpn_id: "{{ EVPN_ID }}"
      ip_address: "{{ BVI_IP }}"
      prefix_mask: "{{ MASK }}"
