--- 
- 
  connection: network_cli
  gather_facts: false
  hosts: '{{ DataCenter }}'
   
  vars: 
    customer_name: "{{ CustomerName }}"
    data_center: "{{ DataCenter }}"
    evpn_id: "{{ EVPN_ID }}"
    ip_address: "{{ BVI_IP }}"
    prefix_mask: "{{ MASK }}"
        
  tasks:
        
    - name: "Config Router EVPN"
      iosxr_config: 
        lines:
          - evi {{evpn_id}}
          - control-word-disable
          - advertise-mac
        parents: evpn
        
    - name: "Config Bundle Interface"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - encapsulation dot1q {{evpn_id}}
          - rewrite ingress tag pop 1 symmetric
        parents: interface Bundle-Ether6.{{evpn_id}} l2transport
        
    - name: "Config L2VPN"
      iosxr_config: 
        lines:
          - "bridge group METRO-E"
          - bridge-domain {{customer_name}}
          - interface Bundle-Ether6.{{evpn_id}}
          - routed interface BVI{{evpn_id}}
          - evi {{evpn_id}}
        parents: l2vpn
    
    
   
        
