---
- name: Run IOS-XR CLI command from variable
  hosts: IOSXR
  gather_facts: false
  
  vars: 
    cli_command: "{{ Command }}"

  tasks:
  - name: Execute the CLI command
    iosxr_command:
      commands:
        - "{{ cli_command }}"
    register: command_output
    
  - name: Print the command output
    debug:
      msg: "{{ command_output.stdout }}"
