---
- name: Run IOS-XR CLI command from variable
  hosts: WAT_N_ASR
  gather_facts: false
  collections:
    - cisco.iosxr

  vars: 
    cli_command: "{{ Command }}"

  tasks:
  - name: Execute the CLI command
    cisco.iosxr.iosxr_command:
      commands:
        - "{{ cli_command }}"
      register: command_output
    
  - name: Print the command output
    debug:
      msg: "{{ command_output.stdout }}"
