---
- name: Run IOS-XR CLI command from variable
  hosts: IOSXR
  gather_facts: false
  
  vars: 
    cli_command: "{{ Command }}"

  tasks:
  - name: Execute the CLI command
    iosxr_command:
      commands:
        - "{{ cli_command }}"
    register: command_output

  - name: Split and format the output for readability
    set_fact:
      formatted_output: "{{ command_output.stdout[0].splitlines() }}"

  - name: Display the formatted output
    debug:
      msg: "{{ formatted_output }}"
