---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: LAB
  tasks:

    - name: Get config for IOSXR devices
      iosxr_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
