--- 
- name: "Reserve IP(s)"
  connection: local
  hosts: localhost
  gather_facts: False 
  
  vars:
    customer_name: "{{CIRCUIT_DESC}}"
  
  tasks:
  
  - name: "Lookup IP"
    setfact:
      ip_address: {{ item.value.prefix }}
    loop: "{{ query('netbox.netbox.nb_lookup', 'prefixes', api_filter='description=' ~ customer_name, api_endpoint='http://netbox.truvista.net:8085', token='9a9f4b51cfa1fc1f3501cb28fd8b86b64aef05f2', validate_certs='False') }}"
  
  - name: "Config BVI Interface for Richland"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - host-routing
          - ipv4 address {{ip_address}}
          - arp timeout 30
          - mac-address 9ce1.76a4.12
        parents: interface BVI 444
