--- 
- name: "Provision Switches"
  connection: network_cli
  gather_facts: false
  hosts: '{{ switch_group }}'
    
  vars: 
    switch_group: "{{ SWITCHES }}"
    switch_position: "{{ SWITCH }}"
    interface_num: "{{ INTERFACE }}"
    interface_des: "{{ DESCRIPTION }}"
    vlans: "{{ VLANS }}"
    y: "{{ '9' if switch_group == 'Omega_HE_Nexus' else '8' }}"
    
  tasks:
  
    - name: Add Vlans to database
      nxos_command:
         commands: 
           - config t
           - command: vlan {{ vlans }}
        
  
    - name: Set port to layer 2
      nxos_interfaces:
        config:
          - name: "{{ interface_num }}"
            description: "{{ interface_des }}"
            enabled: true
            mode: layer2
        admin_state: up
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Add Vlans to customer port
      nxos_command:
         commands:
           - config t
           - command: int {{ interface_num }}
           - command: switchport trunk allowed vlan add {{ vlans }}
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Add Vlans to router uplink
      nxos_command:
         commands:
           - config t
           - command: int port-channel {{y}} 
           - command: switchport trunk allowed vlan add {{ vlans }}
          
    - name: Add Vlans to vPC link
      nxos_command:
         commands:
           - config t
           - command: int port-channel{{y}}{{y}}
           - command: switchport trunk allowed vlan add {{ vlans }}
              
    - name: "Register config changes to variable"
      nxos_command:
        commands:
          - command: show diff rollback-patch startup-config running-config | exc class-map
      register: changes
      delegate_to: "{{ groups[switch_group][switch_position] }}"
        
    - name: "Write configuration changes to a file"
      copy: 
        content: "{{ changes.stdout | replace('\\n', '\n') }}"
        dest: /var/local/customers/{{interface_des}}/{{interface_des}}_switch{{switch_position}}.txt
        mode: 0666
     
    - name: Save run-config
      nxos_config:
        save_when: always  
      
      
