--- 
- name: "Provision Switches"
  connection: network_cli
  gather_facts: false
  hosts: '{{ switch_group }}'
    
  vars: 
    switch_group: "{{ SWITCHES }}"
    switch_position: "{{ SWITCH }}"
    interface_num: "{{ INTERFACE }}"
    interface_des: "{{ DESCRIPTION }}"
    vlans: "{{ VLANS }}"
    y: "{{ '8' if switch_group == 'Chester_CO_POD2' else '6' }}"
    
  tasks:
  
    - name: Add Vlans to database
      nxos_vlan:
        vlan_range: "{{ vlans }}"
  
    - name: Set port to layer 2
      nxos_interface:
        name: "{{ interface_num }}"
        description: "{{ interface_des }}"
        mode: layer2
        admin_state: up
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Add Vlans to customer port
      nxos_l2_interface:
        name: "{{ interface_num }}"
        mode: trunk
        trunk_allowed_vlans: "{{ vlans }}"
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Add Vlans to router uplink
      nxos_l2_interface:
        name: port-channel{{y}}
        mode: trunk
        trunk_vlans: "{{ vlans }}"
          
    - name: Add Vlans to vPC link
      nxos_l2_interface:
        name: port-channel{{y}}{{y}}
        mode: trunk
        trunk_vlans: "{{ vlans }}"
      when: (switch_group == "Chester_CO_POD2" or switch_group == "Commerce_Switches" or switch_group == "Richland_Switches" or switch_group == "Gumlog_Switches" or "Great_Falls_SWitches" or "Ridgeway_SWitches")
        
    - name: "Register config changes to variable"
      nxos_command:
        commands:
          - command: show running-config diff
      register: changes
        
    - name: "Write configuration changes to a file"
      copy: 
        content: "{{ changes.stdout | replace('\\n', '\n') }}"
        dest: /var/local/customers/{{interface_des}}/{{interface_des}}_switch{{switch_position}}.txt
        mode: 0666
     
    - name: Save run-config
      nxos_config:
        save_when: always  
      
      
