- name: "Provision Switches"
  hosts: localhost
  vars_files:
    - /etc/ansible/group_vars/evpn_vars.yml
    
  tasks:
  
    - name: Set switch_group to Commerce
      set_fact:
        switch_group: Commerce_Switches
      when: data_center == 'Commerce'
    
    - name: Set switch_group to Gumlog
      set_fact:
        switch_group: Gumlog_Switches
      when: data_center == 'Gumlog'
      
    - name: Set switch_group to Richland
      set_fact:
        switch_group: Richland_Switches
      when: data_center == 'Richland'
      
    - name: Set port to layer 2
      nxos_interface:
        name: Ethernet1/2
        description: 'Configured by Ansible'
        mode: layer2
        admin_state: up
      delegate_to: "{{ groups[switch_group][0] }}"
      
    - name: Test nxos
      nxos_l2_interface:
        name: Ethernet1/2
        mode: trunk
        trunk_vlans: 5-10
      delegate_to: "{{ groups[switch_group][0] }}"
