---
- name: Launch Provision Routers and Switches jobs
  hosts: localhost
  tasks:

    - name: Launch Provision Routers
      tower_job_launch:
        job_template: "Provision EVPN circuit BETA"
        tower_verify_ssl: no
        vars: 
          customer_name: "{{ CustomerName }}"
          data_center: "{{ DataCenter }}"
          evpn_id: "{{ EVPN_ID }}"
          layer_3: "{{ LAYER_3 }}"
          ip_address: "{{ BVI_IP }}"
          prefix_mask: "{{ MASK }}"
   
    - name: Launch Provision Switches
      tower_job_launch:
        job_template: "Provision EVPN Circuit Switches"
        tower_verify_ssl: no
        vars: 
          switch_group: "{{ SWITCHES }}"
          switch_position: "{{ SWITCH }}"
          interface_num: "{{ INTERFACE }}"
          interface_des: "{{ DESCRIPTION }}"
          vlans: "{{ VLANS }}"
