--- 
- name: "Provision Routers"
  connection: network_cli
  gather_facts: false
  hosts: '{{ DataCenter }}'
   
  vars: 
    customer_name: "{{ CustomerName }}"
    data_center: "{{ DataCenter }}"
    evpn_id: "{{ EVPN_ID }}"
    layer_3: "{{ LAYER_3 }}"
    ip_address: "{{ BVI_IP }}"
    prefix_mask: "{{ MASK }}"
      
  tasks:
        
    - name: "Config Router EVPN"
      iosxr_config: 
        lines:
          - evi {{evpn_id}}
          - control-word-disable
          - advertise-mac
        parents: evpn
        
    - name: "Config Bundle Interface for layer 3"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - encapsulation dot1q {{evpn_id}}
          - rewrite ingress tag pop 1 symmetric
        parents: interface Bundle-Ether6.{{evpn_id}} l2transport
      when: layer_3 == 'yes'
      
    - name: "Config Bundle Interface for layer 2"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - encapsulation dot1q {{evpn_id}}
        parents: interface Bundle-Ether6.{{evpn_id}} l2transport
      when: layer_3 == 'no'
        
    - name: "Config L2VPN"
      iosxr_config: 
        lines:
          - bridge-domain {{customer_name}}
          - interface Bundle-Ether6.{{evpn_id}}
          - routed interface BVI{{evpn_id}}
          - evi {{evpn_id}}
        parents:
          - l2vpn
          - bridge group METRO-E
      when: layer_3 == 'yes'
      
    - name: "Config L2VPN"
      iosxr_config: 
        lines:
          - bridge-domain {{customer_name}}
          - interface Bundle-Ether6.{{evpn_id}}
          - evi {{evpn_id}}
        parents:
          - l2vpn
          - bridge group METRO-E
      when: layer_3 == 'no'
        
    - name: "Config BVI Interface for Commerce"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - host-routing
          - ipv4 address {{ip_address}}{{prefix_mask}}
          - arp timeout 30
          - mac-address 9ce1.99.99
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Commerce")
      
    - name: "Config BVI Interface for Gumlog"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - host-routing
          - ipv4 address {{ip_address}}{{prefix_mask}}
          - arp timeout 30
          - mac-address 9ce1.76cf.fcdf
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Gumlog")
      
    - name: "Config BVI Interface for Richland"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - host-routing
          - ipv4 address {{ip_address}}{{prefix_mask}}
          - arp timeout 30
          - mac-address 9ce1.76a4.12
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Richland")
      
    - name: "Config BVI Interface for Chester CO"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Chester_CO")
      
    - name: "Config BVI Interface for Lewisville CO"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Lewisville")
      
    - name: "Config BVI Interface for Great Falls CO"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Great_Falls")
      
    - name: "Config BVI Interface for Winnsboro HE"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Winnsboro")
      
    - name: "Config BVI Interface for Ridgeway CO"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Ridgeway")
      
    - name: "Config BVI Interface for Camden HE"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Camden")
      
    - name: "Config BVI Interface for Toccoa HE"
      iosxr_config: 
        lines:
          - description {{customer_name}}
          - ipv4 address {{ip_address}}{{prefix_mask}}
        parents: interface BVI {{evpn_id}}
      when: (layer_3 == 'yes' and data_center == "Toccoa")
          
    - name: "Config OSPF if layer 3"
      iosxr_config: 
        lines:
          - interface BVI{{evpn_id}}
          - passive enable
        parents:
          - router ospf MPLS
          - area 0
      when: layer_3 == 'yes'
      
    - name: Make vars persistent
      local_action: 
        module: copy 
        content:
          - customer_name: "{ customer_name }}"
          - data_center: "{{ data_center }}"
          - evpn_id: "{{ evpn_id }}"
        dest: /etc/ansible/group_vars/evpn_vars.yml
        mode: 0666
