--- 
- name: "Provision Switches"
  connection: network_cli
  gather_facts: false
  hosts: '{{ switch_group }}'
  vars_files:
    - /etc/ansible/group_vars/evpn_vars.yml
    
  vars: 
    switch_group: "{{ SWITCHES }}"
    switch_position: "{{ SWITCH }}"
    interface_num: "{{ INTERFACE }}"
    interface_des: "{{ DESCRIPTION }}"
    vlans: "{{ VLANS }}"
    
  tasks:
  
    - name: Set port to layer 2
      nxos_interface:
        name: "{{ interface_num }}"
        description: "{{ interface_des }}"
        mode: layer2
        admin_state: up
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Test nxos
      nxos_l2_interface:
        name: "{{ interface_num }}"
        mode: trunk
        trunk_vlans: "{{ vlans }}"
      delegate_to: "{{ groups[switch_group][switch_position] }}"
