--- 
- name: "Provision Switches"
  connection: network_cli
  gather_facts: false
  hosts: '{{ switch_group }}'
  vars_files:
    - /etc/ansible/group_vars/evpn_vars.yml
    
  vars: 
    customer_name: "{{ CustomerName }}"
    switch_group: "{{ SWITCHES }}"
    interface_num: "{{ INTERFACE }}"
    vlans: "{{ VLANS }}"
    
  tasks:
  
    - name: Set switch_group to Commerce
      set_fact:
        switch_group: Commerce_Switches
      when: data_center == 'Commerce'
    
    - name: Set switch_group to Gumlog
      set_fact:
        switch_group: Gumlog_Switches
      when: data_center == 'Gumlog'
      
    - name: Set switch_group to Richland
      set_fact:
        switch_group: Richland_Switches
      when: data_center == 'Richland'
      
    - name: Set port to layer 2
      nxos_interface:
        name: {{interface_num}}
        description: {{customer_name}}
        mode: layer2
        admin_state: up
      delegate_to: "{{ switch }}"
      
    - name: Test nxos
      nxos_l2_interface:
        name: {{interface_num}}
        mode: trunk
        trunk_vlans: {{ vlans }}
      delegate_to: "{{ switch }}"
