--- 
- name: "Provision Switches"
  connection: network_cli
  gather_facts: false
  hosts: '{{ switch_group }}'
  vars_files:
    - /etc/ansible/group_vars/evpn_vars.yml
    
  vars: 
    switch_group: "{{ SWITCHES }}"
    switch_position: "{{ SWITCH }}"
    interface_num: "{{ INTERFACE }}"
    interface_des: "{{ DESCRIPTION }}"
    vlans: "{{ VLANS }}"
    
  tasks:
  
    - name: Add Vlans to database
      nxos_vlan:
        vlan_id: "{{ vlans }}"
  
    - name: Set port to layer 2
      nxos_interface:
        name: "{{ interface_num }}"
        description: "{{ interface_des }}"
        mode: layer2
        admin_state: up
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Add Vlans to customer port
      nxos_l2_interface:
        name: "{{ interface_num }}"
        mode: trunk
        trunk_allowed_vlans: "{{ vlans }}"
      delegate_to: "{{ groups[switch_group][switch_position] }}"
      
    - name: Add Vlans to router uplink
      nxos_l2_interface:
        name: port-channel6
        mode: trunk
        trunk_vlans: "{{ vlans }}"
          
    - name: Add Vlans to vPC link
      nxos_l2_interface:
        name: port-channel66
        mode: trunk
        trunk_vlans: "{{ vlans }}"
        save_when: modified
      
      
