--- 
- name: "Reserve IP(s)"
  connection: local
  hosts: localhost
  gather_facts: False
  
  vars:
    location: "{{ LOCATION }}"
    description: "{{CIRCUIT_DESC}}"
    prefix_length: "{{PREFIX}}"
  
  tasks:
  
    - name: Get a new available IP inside MGMT vlan 2002
      netbox.netbox.netbox_ip_address:
        netbox_url: http://netbox.truvista.net:8085
        validate_certs: False
        netbox_token: 9a9f4b51cfa1fc1f3501cb28fd8b86b64aef05f2
        data:
          prefix: 172.18.0.0/22
          description: "{{ description }}"
        state: new
      register: IPAddress
      when: location == "MGMT"
      
      
    - name: Get a new prefix when circuit is South Carolina
      netbox.netbox.netbox_ip_address:
        netbox_url: http://netbox.truvista.net:8085
        validate_certs: False
        netbox_token: 9a9f4b51cfa1fc1f3501cb28fd8b86b64aef05f2
        data:
          parent: "206.74.207.0/24"
          prefix_length: "{{ prefix_length }}"
          description: "{{ description }}"
        state: new
        first_available: yes
      register: prefix
      when: location == "South_Carolina"
      
      
    - name: Get a new prefix when circuit is Georgia
      netbox.netbox.netbox_ip_address:
        netbox_url: http://netbox.truvista.net:8085
        validate_certs: False
        netbox_token: 9a9f4b51cfa1fc1f3501cb28fd8b86b64aef05f2
        data:
          parent: "192.96.63.0/24"
          prefix_length: "{{ prefix_length }}"
          description: "{{ description }}"
        state: new
        first_available: yes
      register: prefix
      when: location == "Georgia"
      
    - name: Print MGMT IP reserved
      debug:
        msg: "The IP address reserved for {{ description }} is {{ IPAddress }}"
      when: location == "MGMT"

