--- 
- name: "View Port Mirrors"
  connection: network_cli
  gather_facts: false
  hosts: Chester_HE_Nexus_Pod_1   
    
  tasks:
  
    - name: Show current monitor sessions
      nxos_command:
        commands:
        - show running-config monitor all
        register: monitor
    - debug:
        var: monitor.stdout_lines
