--- 
- 
  connection: network_cli
  gather_facts: false
  hosts: LAB
  tasks: 
    - name: "Rewrite ACL"
     vars:
        - Target_IP:  "{{ TargetIP | default(None) }}"
      iosxr_command: 
        commands: 
          - "config t"
          - "ipv4 access-list subsentio"
          - "10 permit ipv4 host Target_IP any capture"
          - "20 permit ipv4 any host Target_IP capture"
          - commit
          - end
