--- 
- 
  connection: network_cli
  gather_facts: false
  hosts: LAB_ASR_9010
  tasks: 
    - name: "Rewrite ACL"
      iosxr_config: 
        lines:
          - 10 permit ipv4 host 1.1.1.1 any capture
          - 20 permit ipv4 any host 1.1.1.1 capture
        parents: ipv4 access-list subsentio
        
    - name: "Commit"
      iosxr_command:
        commands:
          - commit
